// Emits report.md. Committed to the repo so a fluent reviewer can read it on
// GitHub without running anything, and so a rerun after fixes produces a diff
// showing exactly which findings cleared.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Finding, Severity } from './free-checks';
import { bucket } from './similarity';

const REPORT_PATH = resolve(import.meta.dirname, 'report.md');

export type MtRow = {
    key: string;
    original: string;   // the en.ts value (or phrasebook english)
    translated: string; // the pa value (or phrasebook gurmukhi)
    back: string;       // machine back-translation
    score: number;
};

export type ReportInput = {
    counts: { en: number; pa: number; paLatn: number; phrases: number };
    findings: Finding[];
    dictRows: MtRow[];
    phraseRows: MtRow[];
    mtSkipped: boolean;
    estimatedChars: number;
    billedChars: number;
    cacheHits: number;
    totalCharsBilled: number;
    cacheEntries: number;
    skipLists: { mt: string[]; latinOk: string[] };
};

function cell(value: string, max = 80): string {
    const flat = value.replace(/\s+/g, ' ').trim();
    const clipped = flat.length > max ? flat.slice(0, max - 1) + '…' : flat;
    return clipped.split('|').join('\\|');
}

const SEVERITY_ORDER: Record<Severity, number> = { error: 0, warn: 1, info: 2 };

function findingSection(title: string, findings: Finding[]): string {
    if (findings.length === 0) return `### ${title}\n\nNo findings.\n`;
    const sorted = [...findings].sort(
        (a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity] || a.path.localeCompare(b.path)
    );
    const lines = sorted.map(f => `| ${f.severity} | \`${cell(f.path, 60)}\` | ${cell(f.detail, 110)} |`);
    return [
        `### ${title} (${findings.length})`,
        '',
        '| severity | key | detail |',
        '| --- | --- | --- |',
        ...lines,
        '',
    ].join('\n');
}

function mtSection(title: string, rows: MtRow[], originalLabel: string, translatedLabel: string): string {
    if (rows.length === 0) return `### ${title}\n\nNo rows.\n`;
    const sorted = [...rows].sort((a, b) => a.score - b.score);
    const review = sorted.filter(r => bucket(r.score) === 'review').length;
    const skim = sorted.filter(r => bucket(r.score) === 'skim').length;
    const lines = sorted.map(
        r => `| ${r.score.toFixed(2)} | \`${cell(r.key, 50)}\` | ${cell(r.original)} | ${cell(r.translated)} | ${cell(r.back)} |`
    );
    return [
        `### ${title} (${rows.length})`,
        '',
        `**${review}** below 0.35 (review first) · **${skim}** between 0.35 and 0.55 (skim) · **${rows.length - review - skim}** at 0.55+ (likely fine)`,
        '',
        `| score | key | ${originalLabel} | ${translatedLabel} | back-translation |`,
        '| --- | --- | --- | --- | --- |',
        ...lines,
        '',
    ].join('\n');
}

export function writeReport(input: ReportInput): string {
    const byCheck = (name: string) => input.findings.filter(f => f.check === name);
    const errors = input.findings.filter(f => f.severity === 'error').length;

    const md = [
        '# i18n audit report',
        '',
        '> Generated by `npm run audit:i18n`. Do not edit by hand — rerun instead.',
        '>',
        '> Intentionally carries no timestamp: the content then depends only on the',
        '> strings and the cache, so a rerun after fixes produces a diff showing',
        '> exactly which findings cleared instead of one noisy line every time.',
        '',
        '## Summary',
        '',
        '| metric | value |',
        '| --- | --- |',
        // Stated first and plainly: a reader landing on "0 findings" must not
        // mistake a free-checks-only run for a full audit.
        `| mode | ${input.mtSkipped ? '**dry run** — back-translation not yet run' : 'full audit'} |`,
        `| strings enumerated (en / pa / pa-latn) | ${input.counts.en} / ${input.counts.pa} / ${input.counts.paLatn} |`,
        `| phrasebook entries | ${input.counts.phrases} |`,
        `| findings (errors) | ${input.findings.length} (${errors}) |`,
        `| characters billed this run | ${input.mtSkipped ? '0 (dry run)' : input.billedChars} |`,
        `| cache hits this run | ${input.cacheHits} |`,
        `| cumulative characters billed | ${input.totalCharsBilled} |`,
        `| cache entries | ${input.cacheEntries} |`,
        '',
        ...(input.mtSkipped
            ? [`> **Dry run** — no API calls were made. A full run would translate roughly **${input.estimatedChars} characters** that are not yet cached.`, '']
            : []),
        '## Free checks',
        '',
        '_No API calls. These catch what machine translation cannot see._',
        '',
        findingSection('Placeholder parity', byCheck('placeholder-parity')),
        findingSection('Script sanity', byCheck('script-sanity')),
        findingSection('Community spelling drift', byCheck('spelling-drift')),
        findingSection('Length-ratio outliers', byCheck('length-ratio')),
        '## Machine back-translation',
        '',
        input.mtSkipped
            ? '_Skipped in this dry run._\n'
            : [
                mtSection('Dictionary (pa → en vs en.ts)', input.dictRows, 'en.ts', 'pa.ts'),
                mtSection('Phrasebook (gurmukhi → en vs english)', input.phraseRows, 'english', 'gurmukhi'),
            ].join('\n'),
        '## Methodology',
        '',
        '- **Back-translation is not ground truth.** A low score compares one machine translation against a human-facing string; it flags *where to look*, not what is wrong. Idiomatic translations legitimately score low.',
        '- The Fateh (`Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh`) is stripped from both sides before scoring — it appears verbatim in every lens greeting and would otherwise drag them all to the bottom.',
        '- **`pa-latn.ts` cannot be machine-audited.** Cloud Translation neither romanizes Punjabi nor reliably reads romanized Punjabi, so its coverage here is the free checks only — placeholder parity, script bleed, length ratios, and spelling drift.',
        `- Skipped from back-translation: ${input.skipLists.mt.map(p => `\`${p}\``).join(', ') || '(none)'}. Allowed to be Latin in \`pa.ts\`: ${input.skipLists.latinOk.map(p => `\`${p}\``).join(', ') || '(none)'}.`,
        '',
        // No filter(Boolean) here: intentional blank lines are what keep GFM
        // from swallowing a heading into the table above it.
    ].join('\n');

    writeFileSync(REPORT_PATH, md, 'utf8');
    return REPORT_PATH;
}
